import os
import flet as ft
from tema import COLORES, ESTILOS, aplicar_estilo, crear_gradiente_lineal

assets_dir = "assets"
upload_dir = os.path.join(assets_dir,"uploads")
usuario_logueado = "" 
ruta_actual = os.getcwd()

# Exportar las variables del tema para acceso global
colores = COLORES
estilos = ESTILOS

# Diccionario de traducción de códigos hexadecimales a nombres de colores en español
color_names = {
    "#67ab59": "Verde",
    "#bf2cb4": "Morado",
    "#dfbd36": "Amarillo cálido",
    "#ff0000": "Rojo",
    "#00ff00": "Verde",
    "#0000ff": "Azul",
    "#ffff00": "Amarillo",
    "#ff00ff": "Magenta",
    "#00ffff": "Cian",
    "#000000": "Negro",
    "#ffffff": "Blanco",
    "#808080": "Gris",
    "#800000": "Marrón",
    "#808000": "Oliva",
    "#008000": "Verde oscuro",
    "#800080": "Púrpura",
    "#008080": "Verde azulado",
    "#000080": "Azul marino",
    "#ffa500": "Naranja",
    "#a52a2a": "Marrón",
    "#ffc0cb": "Rosa",
    "#d2691e": "Chocolate",
    "#8b4513": "Marrón saddlebrown",
    "#4682b4": "Azul acero",
    "#4b0082": "Índigo",
    "#7cfc00": "Verde césped",
    "#6a5acd": "Azul pizarra",
    "#ff6347": "Tomate",
    "#ff4500": "Naranja rojizo",
    "#da70d6": "Orquídea",
    "#32cd32": "Verde lima",
    "#9370db": "Púrpura medio",
    "#f0e68c": "Caqui",
    "#e6e6fa": "Lavanda",
    "#fffacd": "Amarillo limón",
    "#f5f5dc": "Beige",
    "#f5deb3": "Trigo",
    "#d3d3d3": "Gris claro",
    "#a9a9a9": "Gris oscuro",
    "#2f4f4f": "Gris pizarra oscuro",
    "#8b0000": "Rojo oscuro",
    "#006400": "Verde oscuro",
    "#00008b": "Azul oscuro",
    "#ff8c00": "Naranja oscuro",
    "#9932cc": "Orquídea oscuro",
    "#8b008b": "Magenta oscuro",
    "#e9967a": "Salmón oscuro",
    "#8fbc8f": "Verde mar oscuro",
    "#483d8b": "Azul pizarra oscuro",
    "#cd853f": "Madera de Perú",
    "#708090": "Gris pizarra",
    "#f4a460": "Marrón arena",
    "#fa8072": "Salmón",
    "#20b2aa": "Verde mar claro",
    "#87cefa": "Azul cielo claro",
    "#778899": "Gris pizarra claro",
    "#b0c4de": "Azul acero claro",
    "#ffffe0": "Amarillo claro",
    "#00ff7f": "Verde primavera",
    "#4169e1": "Azul real",
    "#f08080": "Coral claro",
    "#cd5c5c": "Rojo indio",
    "#dc143c": "Carmesí",
    "#ff1493": "Rosa profundo",
    "#c71585": "Violeta medio",
    "#db7093": "Violeta pálido",
    "#ff7f50": "Coral",
    "#ff69b4": "Rosa intenso",
    "#ffb6c1": "Rosa claro",
    "#ffa07a": "Salmón claro",
    "#ee82ee": "Violeta",
    "#dda0dd": "Ciruela",
    "#98fb98": "Verde pálido",
    "#afeeee": "Turquesa pálido",
    "#add8e6": "Azul claro",
    "#b0e0e6": "Azul polvora",
    "#87ceeb": "Azul cielo",
    "#6495ed": "Aciano",
    "#40e0d0": "Turquesa",
    "#48d1cc": "Turquesa medio",
    "#00ced1": "Turquesa oscuro",
    "#5f9ea0": "Cadete azul",
    "#7fffd4": "Aguamarina",
    "#66cdaa": "Aguamarina medio",
    "#3cb371": "Verde mar medio",
    "#2e8b57": "Verde mar",
    "#228b22": "Verde bosque",
    "#556b2f": "Verde oliva oscuro",
    "#6b8e23": "Verde oliva",
    "#bdb76b": "Caqui oscuro",
    "#daa520": "Vara de oro",
    "#b8860b": "Vara de oro oscuro",
    "#cd853f": "Perú",
    "#d2b48c": "Bronceado",
    "#bc8f8f": "Rosado",
    "#a0522d": "Siena",
    "#8b4513": "Marrón silla de montar",
    "#4b0082": "Índigo",
    "#9400d3": "Violeta oscuro",
    "#9932cc": "Orquídea oscuro",
    "#ba55d3": "Orquídea medio",
    "#da70d6": "Orquídea",
    "#c71585": "Violeta medio",
    "#ff00ff": "Fucsia",
    "#ff69b4": "Rosa intenso",
    "#ff1493": "Rosa profundo",
    "#db7093": "Violeta pálido",
    "#f08080": "Coral claro",
    "#cd5c5c": "Rojo indio",
    "#dc143c": "Carmesí",
    "#b22222": "Ladrillo refractario",
    "#8b0000": "Rojo oscuro",
    "#800000": "Granate",
    "#a52a2a": "Marrón",
    "#d2691e": "Chocolate",
    "purple": "Morado",
    "warm yellow": "Amarillo cálido",
    "#red": "Rojo",
    "#green": "Verde",
    "#blue": "Azul",
    "#yellow": "Amarillo",
    "#magenta": "Magenta",
    "#cyan": "Cian",
    "#black": "Negro",
    "#white": "Blanco",
    "#gray": "Gris",
    "#grey": "Gris",
    "#brown": "Marrón",
    "#olive": "Oliva",
    "#dark green": "Verde oscuro",
    "#purple": "Púrpura",
    "#teal": "Verde azulado",
    "#navy": "Azul marino",
    "#navy blue": "Azul marino",
    "#orange": "Naranja",
    "#pink": "Rosa",
    "#chocolate": "Chocolate",
    "#saddle brown": "Marrón saddlebrown",
    "#steel blue": "Azul acero",
    "#indigo": "Índigo",
    "#lawn green": "Verde césped",
    "#slate blue": "Azul pizarra",
    "#tomato": "Tomate",
    "#orange red": "Naranja rojizo",
    "#orchid": "Orquídea",
    "#lime green": "Verde lima",
    "#medium purple": "Púrpura medio",
    "#khaki": "Caqui",
    "#lavender": "Lavanda",
    "#lemon chiffon": "Amarillo limón",
    "#beige": "Beige",
    "#wheat": "Trigo",
    "#light gray": "Gris claro",
    "#light grey": "Gris claro",
    "#dark gray": "Gris oscuro",
    "#dark grey": "Gris oscuro",
    "#dark slate gray": "Gris pizarra oscuro",
    "#dark slate grey": "Gris pizarra oscuro",
    "#dark red": "Rojo oscuro",
    "#dark green": "Verde oscuro",
    "#dark blue": "Azul oscuro",
    "#dark orange": "Naranja oscuro",
    "#dark orchid": "Orquídea oscuro",
    "#dark magenta": "Magenta oscuro",
    "#dark salmon": "Salmón oscuro",
    "#dark sea green": "Verde mar oscuro",
    "#dark slate blue": "Azul pizarra oscuro",
    "#peru": "Madera de Perú",
    "#slate gray": "Gris pizarra",
    "#slate grey": "Gris pizarra",
    "#sandy brown": "Marrón arena",
    "#salmon": "Salmón",
    "#light sea green": "Verde mar claro",
    "#light sky blue": "Azul cielo claro",
    "#light slate gray": "Gris pizarra claro",
    "#light slate grey": "Gris pizarra claro",
    "#light steel blue": "Azul acero claro",
    "#light yellow": "Amarillo claro",
    "#spring green": "Verde primavera",
    "#royal blue": "Azul real",
    "#light coral": "Coral claro",
    "#indian red": "Rojo indio",
    "#crimson": "Carmesí",
    "#deep pink": "Rosa profundo",
    "#medium violet red": "Violeta medio",
    "#pale violet red": "Violeta pálido",
    "#coral": "Coral",
    "#hot pink": "Rosa intenso",
    "#light pink": "Rosa claro",
    "#light salmon": "Salmón claro",
    "#violet": "Violeta",
    "#plum": "Ciruela",
    "#pale green": "Verde pálido",
    "#pale turquoise": "Turquesa pálido",
    "#light blue": "Azul claro",
    "#powder blue": "Azul polvora",
    "#sky blue": "Azul cielo",
    "#cornflower blue": "Aciano",
    "#turquoise": "Turquesa",
    "#medium turquoise": "Turquesa medio",
    "#dark turquoise": "Turquesa oscuro",
    "#cadet blue": "Cadete azul",
    "#aquamarine": "Aguamarina",
    "#medium aquamarine": "Aguamarina medio",
    "#medium sea green": "Verde mar medio",
    "#sea green": "Verde mar",
    "#forest green": "Verde bosque",
    "#dark olive green": "Verde oliva oscuro",
    "#olive drab": "Verde oliva",
    "#dark khaki": "Caqui oscuro",
    "#goldenrod": "Vara de oro",
    "#dark goldenrod": "Vara de oro oscuro",
    "#peru": "Perú",
    "#tan": "Bronceado",
    "#rosy brown": "Rosado",
    "#sienna": "Siena",
    "#saddle brown": "Marrón silla de montar",
    "#dark violet": "Violeta oscuro",
    "#dark orchid": "Orquídea oscuro",
    "#medium orchid": "Orquídea medio",
    "#orchid": "Orquídea",
    "#medium violet red": "Violeta medio",
    "#fuchsia": "Fucsia",
    "#hot pink": "Rosa intenso",
    "#deep pink": "Rosa profundo",
    "#pale violet red": "Violeta pálido",
    "#light coral": "Coral claro",
    "#indian red": "Rojo indio",
    "#crimson": "Carmesí",
    "#firebrick": "Ladrillo refractario",
    "#dark red": "Rojo oscuro",
    "#maroon": "Granate",
    "#brown": "Marrón",
    "#chocolate": "Chocolate",
}

# Función para aplicar el tema a la página
def aplicar_tema_a_pagina(page: ft.Page):
    """
    Aplica el tema global a una página de Flet
    
    Args:
        page: Objeto ft.Page al que aplicar el tema
    """
    # Crear un nuevo tema si no existe
    if page.theme is None:
        page.theme = ft.Theme()

    # Configurar tema de la página
    page.theme.color_scheme_seed = colores["primario"]
    #page.theme.visual_density = ft.ThemeVisualDensity.COMFORTABLE
    page.theme.visual_density = ft.VisualDensity.COMFORTABLE
    

    # Asegurarse de que color_scheme existe
    if page.theme.color_scheme is None:
        page.theme.color_scheme = ft.ColorScheme()

    # Configurar colores personalizados
    page.theme.color_scheme.primary = colores["primario"]
    page.theme.color_scheme.secondary = colores["secundario"]
    
    # Configurar fuentes y otros estilos globales si es necesario
    # page.fonts = {"Roboto": "/fonts/Roboto-Regular.ttf"}
    
    # Actualizar la página para aplicar los cambios
    page.update()